project:
  type: website
  #output-dir: docs  #- para cambiar la carpeta donde se creará el blog

website:
  title: "Mi blog (aún en pruebas)"
  #favicon: imagenes/ababol_redondeado.ico
  #site-url: https://perezp44.github.io/pjperez.blog.2022/  #-Github Pages
  #repo-url: https://github.com/perezp44/pjperez.blog.2022  #-Github Pages
  navbar:
    logo: "profile.jpg"
    #background: primary    #- pink (el backgroung de la navbar)
    left: 
      - text: "Docencia"
        href: docencia.qmd
      -  text: "Más cosas"
         menu:
          - text: "Docencia 2"
            href: docencia.qmd
          - text: "Docencia 3"
            href: docencia.qmd
          - text: "---"
          - text: "Docencia 4"
            href: docencia.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/<tu-usuario-github>
      - icon: twitter
        href: https://twitter.com/<tu-usuario twitter>
      - icon: envelope
        url: "mailto:<tu-mail@uv.es>"
  page-footer:
    left: "© 2022 Pedro J. Pérez"
    center: "Hecho con [quarto](https://quarto.org)"
    right:
      - icon: github
        href: https://github.com/<tu-usuario-github>
      - icon: twitter
        href: https://twitter.com/<tu-usuario-twitter>
      - icon: envelope
        url: "mailto:<tu-email@uv.es>"
      - text: <i class="ai ai-google-scholar" role="img"></i>
        href: https://scholar.google.de/citations?user=<tu-usuario>
      - text: <i class="ai ai-orcid" role="img"></i>
        href: https://orcid.org/<tu-usuario>

format:
  html:
    #theme: ember.scss 
    theme: 
    - minty  #- listado de themes: https://quarto.org/docs/output-formats/html-themes.html
    - custom.scss  #- este archivo no existe (ya pondré uno, igual!!)
    css: 
    - styles.css
    toc: true
    #- https://quarto.org/docs/output-formats/html-code.html#highlighting
    highlight-style: a11y
    
#editor: visual