---
title: "Materiales para el taller"
---



:::: columns
::: {.column width="74%"}

#### 0. [Intro](./taller/00_taller_slides.html){target="_blank"} (15 min)

#### 1. [Creación de un blog básico: mi blog en 3 minutos](./taller/01_taller_crear-blog-basico.qmd){target="_blank"} (10 min)

#### 2. [Tuneado básico del blog](./taller/02_taller_tuneado-basico.qmd){target="_blank"} (15 min + 15 min de Práctica). 

#### 3. [Convirtiendo el blog en una web académica](./taller/03_taller_convertir-en-web.qmd){target="_blank"} (5 min)

#### 4. [Workflow: ¿cómo crear un post?](./taller/04_taller_crear-post.qmd){target="_blank"} (5 min)

#### 5. [Escribiendo posts: practicando con Quarto](./taller/05_taller_escribir-posts.qmd){target="_blank"} (15 min + 15 min de Práctica)


#### 6. [Tuneado del blog](./taller/06_taller_tuneado-del-blog.qmd){target="_blank"} (15 min)

#### 7. [Opciones de alojamiento](./taller/07_taller_alojamiento.qmd){target="_blank"} (10 min)


<br>

----------------------


#### [Slides para presentación](./taller/slides_tareas_01.html){target="_blank"} 


#### [Plantilla para escribir con Quarto](./taller/09_taller_plantilla_escribir_quarto.qmd){target="_blank"} 


<br>

Seguramente usaremos esta [Etherpad](https://etherpad.wikimedia.org/p/curso_intro_DS_UV){target="_blank"}.


:::

::: {.column width="26%"}

**Materiales** del taller **Mi primer blog con Quarto** preparados para el [I Congreso & XII Jornadas de Usuarios de R](http://r-es.org/12jr/){target="_blank"} celebradas en Córdoba (Spain), 23-25 de noviembre de 2022.

El taller está pensado para realizar con [R](https://cran.r-project.org/){target="_blank"}. Se utilizará el IDE [RStudio](https://www.rstudio.com/products/rstudio/){target="_blank"} y [Quarto](https://quarto.org/){target="_blank"}. Se recomienda tener instaladas **versiones recientes** de los 3 programas. En la sección `Setup` tienes instrucciones para instalar el software necesario para el taller

Hay unas slides de introducción y 7 tutoriales. Además, hay unas slides para utilizar por el presentador durante el taller. Adicionalmente hay un blog con posts para servir de ejemplo en el marco del turorial nº 5.
:::

::::

<br>



