---
title: ""
---

Desde que **Quarto** se hizo publico con [We don't talk about Quarto](https://www.apreshill.com/blog/2022-04-we-dont-talk-about-quarto/) ha sido un no parar de workshops, posts, etc... en esta página tienes una selección de recursos sobre Quarto. Obviamente la principal referencia es la [web de Quarto](https://quarto.org/). En ella hay, entre otras secciones, una [Guide](https://quarto.org/docs/guide/), una [Reference](https://quarto.org/docs/reference/) y una [Gallery](https://quarto.org/docs/gallery/).

Entre los materiales que he visto destacar lo siguientes:


- [AWESOME Quarto](https://github.com/mcanouil/awesome-quarto): un listado muy extenso de recursos Quarto hecho por Mickaël Canouil.

- [Quarto tip a day](http://mine-cetinkaya-rundel.github.io/quarto-tip-a-day/): Un blog de Mine Çetinkaya-Rundel con consejos y tips sobre Quarto.


- [Building a blog with Quarto](https://ivelasq.quarto.pub/building-a-blog-with-quarto/): un workshop de Isabella Velásquez acerca de cómo construir un blog con Quarto. El [repo de los ejercicios](https://github.com/ivelasq/build-your-own-blog-exercises), [video](https://www.youtube.com/watch?v=CVcvXfRyfE0) y [RStudioCloud project]( https://rstudio.cloud/project/4404816) .

- [ Get Started with Quarto](https://jthomasmock.github.io/quarto-2hr-webinar/): un workshop de Thomas Mock. El [video](https://youtu.be/yvi5uXQMvu4), y [otro video de 3h](https://www.youtube.com/watch?v=KnwQFph3s94&list=PL4IzsxWztPdmSeucR67EH_8_hzldqYZX4&index=8).

- [Beautiful Reports and Presentations with Quarto](https://thomasmock.quarto.pub/reports-presentations/#/title-slide): un workshop de Thomas Mock. El [video](https://www.youtube.com/watch?v=hbf7Ai3jnxY) y el [repo](https://github.com/jthomasmock/quarto-reporting). 

- [100 seconds from zero to public site](https://youtube.com/watch?v=t8qtcDyCRFA&t=1s): video de Thomas Mock donde crea una web con Quarto en 100 segundos.

- [Introducción a RMarkdown, creando reportes con R y Python en RStudio](https://www.youtube.com/watch?v=d8jSN998Mtw): workshop de Renzo Cáceres para LatinR 2022.

- [Making shareable documents with Quarto](https://openscapes.github.io/quarto-website-tutorial/): una web de Openscapes. 


