---
title: "Setup"
---


::: {.callout-note collapse="false" appearance="default" icon="false"}
## Contexto

- Setup para el taller **Mi primer blog con Quarto** impartido en el [I Congreso & XII Jornadas de Usuarios de R](http://r-es.org/12jr/){target="_blank"} celebradas en Córdoba (Spain), 23-25 de noviembre de 2022.

-   El taller está pensado para realizar con [R](https://cran.r-project.org/){target="_blank"}. Se utilizará el IDE [RStudio](https://www.rstudio.com/products/rstudio/download/#download){target="_blank"} y [Quarto](https://quarto.org/docs/get-started/){target="_blank"}. Se recomienda tener instaladas **versiones recientes** de los 3 programas.
:::


::: {.callout-important collapse="false" appearance="default" icon="false"}
## Instalación de R, RStudio y Quarto

-   Todos sabemos instalar R y Rstudio, si no fuese así, [aquí](https://perezp44.github.io/intro-ds-22-23-web/mas-recursos/01_instrucciones-instalacion.html){target="_blank"} tienes un tutorial. Sólo tendrías que completar la primera parte del tutorial.

-   Instalación de **Quarto**: si tienes una versión de RStudio superior o igual a RStudio 2022.07.1, ya tienes una versión de Quarto instalada. Si no fuese así, [aquí](https://quarto.org/docs/get-started/){target="_blank"} tienes los instaladores para los principales sistemas operativos.

- Además, para alojar el blog necesitaréis crear una cuenta en [Quarto Pub](https://quartopub.com/) y [Github](https://github.com/).
:::



::: {.callout-warning  appearance="default" icon="true"}
## Advertencia

Voy a **suponer que los asistentes al taller**, y posible lectores, de estos tutoriales **conocen Rmarkdown** y han escrito algún documento `.Rmd`. En ese caso, el paso de `.Rmd` a `.qmd` es sencillo. 

En cualquier caso, [aquí](https://quarto.org/docs/faq/rmarkdown.html) tienes unas FAQ's para usuarios de .Rmd que se preguntan si pasarse a Quarto, y [aquí](https://laderast.github.io/qmd_rmd/#/title-slide) unas slides sobre las diferencias entre `.qmd` y `.Rmd`.

Aquellos que no sepan qué es Rmarkdown pueden empezar por [aquí](https://perezp44.github.io/intro-ds-22-23-web/tutoriales/tt_07_Rmarkdown.html) o [aquí](https://perezp44.github.io/intro-ds-22-23-web/slides/slides_07_rmarkdown.html#1).

:::


<br>
