::: {.callout-note collapse="true" appearance="default" icon="false"}
#### Resumen (tutorial nº 5)

- La **quinta parte del taller** se ocupa de la **escritura de posts** para el blog. 

- Los posts **se han de escribir en formato `.qmd`**; por lo tanto, se repasan  los fundamentos "teóricos" necesarios para escribir este tipo de documentos.

- Nos apoyamos en nuestro **conocimiento previo de la sintaxis Rmarkdown**.

- Se repasan las posibilidades de configurar los documentos por medio de **los 3 YAML's** que pueden afectar a un documento.

-  **Los 3 YAML's** son: Nivel proyecto (`_quarto.yml`), nivel carpeta (`_metadata.yml`) y nivel documento (en el propio encabezamiento del archivo)

- El texto en ficheros `.qmd` es muy similar al de los documentos `.qmd`. Aparecen algunos elementos nuevos que repasaremos en la Práctica

- El código sí presenta novedades: nueva sintaxis (`#|`) y posibilidad de determinar opciones en el YAML.

- Para poder escribir en `.qmd` **hay que practicar**. Vamos a ello

:::