---
title: "Workflow: ¿cómo crear un post?"
subtitle: "(4ª parte del taller [Mi primer blog con Quarto](https://perezp44.github.io/taller.primer.blog/))"
---

{{< include ./_includes/_contexto.qmd >}}


::: {.callout-note collapse="true" appearance="default" icon="false"}
## Recapitulación

-   En esta cuarta parte del taller veremos como crear nuevos posts para el blog.

-   Las anteriores secciones del taller son:

    1. **Intro**: se presenta el taller

    2. **Creación de un blog (básico) con Quarto**: en la segunda parte del taller vimos como crear y alojar un **blog básico** con RStudio y Quarto.
    
    3. **Tuneado básico del blog**. Modificamos ligeramente los ficheros `_quarto.yml`, `index.qmd`, `about.qmd` y `styles.css`.
:::


------------------------------------------------------------------------

<br>

{{< include ./_includes/_tt_04_01_q-haremos.qmd >}}


<br>

El blog que hemos creado con Quarto y que estamos adaptando a nuestras necesidades, contiene de fábrica 2 posts muy sencillos. Sus títulos son: "Welcome to my blog" y "Post with code". 

Más adelante borraremos estos 2 posts, pero ahora mismo los vamos a utilizar de ejemplo para crear un nuevo post. Será en la sección siguiente, de momento veamos donde están los archivos que generan los posts de nuestro blog.

## ¿Donde están los posts del blog?

Los ficheros `.qmd` que generan los posts están en la carpeta `posts` de nuestro Qproject que genera el blog. 

Cada post está en una carpeta diferente. Veámoslo:

{{< include ./_includes/_tt_04_02_carpeta-posts.qmd >}}


Como ves, en la carpeta`posts` hay:

  - una subcarpeta para cada post.
    
  - el archivo `_metadata.yml`. Lo veremos más adelante, pero sirve para generar opciones comunes a todos los posts de la carpeta `posts`.

<br>

## Contenido de cada subcarpeta de `./posts/`

Veamos el contenido de una de las carpetas que generan los posts, por ejemplo la carpeta `/welcome/`:


{{< include ./_includes/_tt_04_03_contenido-1-post.qmd >}}


Como ves, la carpeta `/welcome/` que genera el primer post del blog contiene 2 archivos: 

  - `index.qmd`: es realmente el archivo que genera el post. Repasaremos su contenido más adelante.
  
  - `thumbnail.jpg`: sencillamente un archivo con una imagen que será usado al generar el post.
  
<br>

## Creando un nuevo post


De momento, para generar un nuevo post lo que haremos será crear una nueva subcarpeta dentro de `./posts/`, ponerle nombre y pegar allí los archivos que hay en la carpeta de uno de los dos posts de prueba. Por ejemplo: 






- Bueno, pues ya lo tenemos, ya tenemos un nuevo post. Lo que ocurre es que, como no hemos cambiado el contenido de `index.qmd` ni de `tumbnail.jpg`, resulta que el tercer post de nuestro blog será idéntico al primero, al post de bienvenida.

- Evidentemente puedes cambiar estos archivos para que el tercer post no sea idéntico al primero. Hagámoslo.

{{< include ./_includes/_tt_04_04_tarea-01.qmd >}}


{{< include ./_includes/_tt_04_05_tarea-02.qmd >}}


<br>

En el **siguiente tutorial** veremos en profundidad las posibilidades que nos ofrece Quarto para escribir nuestros posts.

<br>

## Resumen

{{< include ./_includes/_tt_04_06_resumen.qmd >}}







<br>


## Referencias

(Algunos artículos sobre creación de blogs en Quarto)

- [ Eric Ekholm. 2022. Modifying the Default Quarto Blog Structure](https://www.ericekholm.com/posts/demo-quarto-site/)  es una web con blog . GOOOOD


