---
title: "Tuneado básico del blog (4ª parte del taller)"
author: "Pedro J. Pérez"
date: "`r format(Sys.time(), '%d %B, %Y')`"
format: 
  html:
    theme: minty  #- https://quarto.org/docs/output-formats/html-themes.html
    #-https://quarto.org/docs/websites/website-blog.html#themes
    backgroundcolor: "#F1F3F4"
    toc: true
    toc-depth: 3
    toc-location: left
    smooth-scroll: true
    #self-contained: true  #- ya no la usa la nueva version de pandoc
    standalone: true  
    link-external-icon: false
    link-external-newwindow: true
    html-math-method: katex
    citations-hover: false
    footnotes-hover: false
    css: assets/styles.css
comments:
  hypothesis: 
    theme: clean
---

::: {.callout-note collapse="false" appearance="default" icon="false"}
## Contexto

-   Tutorial preparado para el taller **"Mi primer blog con Quarto"** celebrado en Córdoba (Spain), 23-25 de noviembre de 2022. El taller se celebró el jueves 24, 15:15-17:00.

- Este tutorial es sólo una parte del taller. Concretamente la **cuarta parte**.

- En esta cuarta parte del taller vamos a **crear un nuevo post**. 

- El **taller completo** está [aquí]().
:::



::: {.callout-important collapse="false" appearance="default" icon="false"}
## Setup: instalación de R, RStudio y Quarto

-   El taller está pensado para realizar con [R](https://cran.r-project.org/), el IDE [RStudio](https://www.rstudio.com/) y [Quarto](https://quarto.org/), así que tendrán que estar instalados en tu ordenador. Es recomendable tener instaladas **versiones recientes** de los 3 programas.

-   Todos sabemos **instalar R y Rstudio**, si no fuese así, [aquí](https://perezp44.github.io/intro-ds-22-23-web/mas-recursos/01_instrucciones-instalacion.html) tienes un tutorial. Sólo tendrías que completar la primera parte del tutorial.

-   Instalación de **Quarto**: si tienes una versión de RStudio superior o igual a RStudio 2022.07.1, ya tienes una versión de Quarto instalada. Si no fuese así, [aquí](https://quarto.org/docs/get-started/) tienes los instaladores para los principales sistemas operativos.
:::



::: {.callout-note collapse="false" appearance="default" icon="false"}
## Recapitulación

- En esta cuarta parte del taller vamos a **crear un nuevo post**.  

- Las anteriores secciones del taller son

    - Intro
    
    - Creación de un blog (básico) con Quarto:  en la segunda parte del taller vimos como crear un **blog básico** con RStudio y Quarto.
    
    - Tuneado (básico) del blog
:::



<br>

-------------

<br>


::: {.callout-tip collapse="false" appearance="default" icon="false"}
## ¿Qué haremos en este tutorial?

- Escribir un nuevo post

- Aprender a utilizar algunos truquillos de Quarto
:::


<br>

## Creando un nuevo post





## TRUCO

-   casi mejor hacer esto despues de crear un post

-   vamos a transformar nuestro blog en una página web personal con blog

-   para ello solo hay que :

    1)  cambiar el nombre del fichero `index.qmd` a `blog.qmd`

    2)  cambiar el nombre del fichero `about.qmd` a `index.qmd`
