---
title: "Alojamiento del blog"
subtitle: "(7ª parte del taller [Mi primer blog con Quarto](https://perezp44.github.io/taller.primer.blog/))"
toc-title: Tutorial nº 7
---

{{< include ./_includes/_contexto.qmd >}}

Al final este tutorial no salió, así que os remito a la [documentación oficial](https://quarto.org/docs/publishing/) de Quarto.

Simplemente decir que publicar el blog en QuartoPub es muy fácil, ya lo hemos hecho, simplemente desde la Terminal hay que ejecutar `quarto render`.

Yo suelo alojar mis proyectos en [Github Pages](https://docs.github.com/en/pages/quickstart). Lo suelo hacer utilizando Git desde RStudio y la Terminal.

Para alojar el blog en Github Pages el blog debe generarse en la carpeta "docs". Para ello, has de poner en el archivo `_quarto.yml` la opción `output-dir: docs` en lugar de `output-dir: _site`. Una vez hecho esto, tienes que alojar toda la carpeta del Qproject en un repositorio de Github; después tendrás, desde las opciones de setup del repositorio, activarla la opción "Pages".

Si hay tiempo y nos animamos lo hacemos en el taller, pero no creo que haya tiempo



<br>


## Some biblio

- [Tutorial Git en curso de reproducibilidad](https://eliocamp.github.io/reproducibility-with-r/materials/day2/01-git/#git-and-github)

- [Guía de instalacion de Git](https://ucsb-meds.github.io/meds-install-windows.html)